### ISSUE TITLE
Mapzen runs without key, then error

### ISSUE THREAD

**Issue by JackDougherty** [ilyankou/geocoder-for-google-sheets#2]
In geocoder, when I run Mapzen the window asking for API key pops up. If I click OK or cancel that window without inserting an API key, it still runs for about 10-11 entries, then produces this error:

![leaflet_maps_with_google_sheets_development_-_google_sheets](https://cloud.githubusercontent.com/assets/649719/23340841/2640fc84-fc0b-11e6-852a-20931d7c47db.png)

**Comment by ilyankou** [comment]
1. I noticed that if you insert an incorrect Mapzen key, you still get the results for the old searches you did with Mapzen, but not with new addresses/queries.

2. https://mapzen.com/documentation/overview/#mapzen-search
Mapzen standard API key is limited to 6 queries per second and 30,000 queries/day. I am not sure why the Error message says '1 allowed', it may have to do with the fact that the key is incorrect. But in general I would expect some error messages popping up when processing large chunks of data - you can make a note in the book saying it's normal since APIs are limited.
